# -*- coding: utf-8 -*-
"""回调（callback typedef）绑定的运行时支持。

生成物 native/src/gen/dh_bind_cb.h —— 被所有 *_cbsNNN.cpp 分片 include。

注意：HEADER 里的注释一律用 ASCII。emit.write_if_changed 以 ascii 编码写出，
且 MSVC 对非 ASCII 源文件可能报 C4819，生成的 C++ 保持纯 ASCII 最省事。

设计要点（都是"我们吃苦"的部分，上游只面对 bind_fXxx(cb) 一个调用）：

1. **单一槽位注册表**：289 个回调共用一个
   `unordered_map<string, nb::object>`。若每个回调各持一个全局
   `nb::object`，会生成 289 份独立模板实例化，MSVC 编译时间会炸；
   共用注册表后 thunk 只需调用宏，几乎不产生新实例化。

2. **GIL 与生命周期分离**：注册（Python 线程，持 GIL）与触发（SDK 工作线程）
   通过 `get()` 返回的 `nb::object` 副本（引用计数 +1）解耦。即使 Python 侧
   在回调执行中途调了 `bind_fXxx(None)` 取消订阅，正在执行的那次调用仍安全。

3. **绕过 nanobind 的返回值转换**（关键）：触发时不用
   `nb::object::operator()`，而是先把参数转成 nb::object，再用 CPython 的
   `PyObject_CallObject` 调用并**丢弃返回值**。

   原因：nanobind 的 `type_caster<nb::object>::from_python` 要求
   `isinstance<nb::object>(src)`（见 nb_cast.h），也就是回调的返回值必须是
   nb::object 的 Python 实例才算合法。实测 `return 0` 恰好通过 isinstance 而
   `return None` / `return "x"` 抛 "bad cast" —— 而 None 才是最自然的返回。
   直接调 PyObject_CallObject 则返回什么都接受，行为可预测。

4. **异常隔离**：用户回调抛出的异常绝不能穿过 C ABI 回到 SDK 线程。
   取回并打印后清空错误状态（PyErr_Fetch/PyErr_Clear）。

5. **参数类型擦除**：注册表存 nb::object，调用点按生成代码已知的实参列表展开。

每条设计背后的具体报错（`0xC0000005` / `bad cast` / C2661 / C2955 …）都记在
`docs/implementation-notes.md` 第一节与第二节。HEADER 内的英文注释会原样进入
生成的 `dh_bind_cb.h`，是该文件的第一手说明。
"""

HEADER = r'''// AUTO-GENERATED from tools/common/dhcb.py -- DO NOT EDIT THIS FILE.
// Edit dhcb.py (the HEADER template) and re-run `python tools/gen_bind.py`;
// anything written here directly is overwritten on the next generation.
#pragma once

#define NOMINMAX
#include <nanobind/nanobind.h>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <exception>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

namespace nb = nanobind;

namespace dhcb {

// Registry. Function-local statics so init order is safe across many TUs.
inline std::mutex &registry_mutex() {
    static std::mutex m;
    return m;
}

inline std::unordered_map<std::string, nb::object> &registry() {
    // Intentionally leaked. This static would otherwise be destroyed during
    // module teardown, i.e. after the interpreter is already partially gone;
    // running ~nb::object then touches freed interpreter state and crashes with
    // 0xC0000005 *after* the script printed its result. Leaking avoids that;
    // subscriptions are dropped explicitly via unbind_fXxx() instead.
    static auto *r = new std::unordered_map<std::string, nb::object>();
    return *r;
}

// Store the callback. Takes nb::object **by value** so the registry owns a
// reference: nb::borrow<T>() does NOT take one (borrow_t), and storing a
// borrowed handle leaves a dangling reference once the caller's lambda is
// collected -> the next SDK callback calls freed memory (0xC0000005).
inline void set(const char *name, nb::object cb) {
    std::lock_guard<std::mutex> lk(registry_mutex());
    auto it = registry().find(name);
    if (it == registry().end()) {
        registry().emplace(name, std::move(cb));
    } else {
        it->second = std::move(cb);
    }
}

inline void clear(const char *name) {
    std::lock_guard<std::mutex> lk(registry_mutex());
    registry().erase(name);
}

// Hand out a refcount+1 copy so it stays valid after the lock is released,
// i.e. even if Python unsubscribes while the callback is running.
inline nb::object get(const char *name) {
    std::lock_guard<std::mutex> lk(registry_mutex());
    auto it = registry().find(name);
    if (it == registry().end())
        return nb::object();
    return it->second;
}

// Is the current thread already attached to the interpreter?
//
// The predicate is deliberately "has a thread state", NOT PyGILState_Check():
// a caller may hand us a thread that already has a tstate it prepared itself
// while the GIL is in fact held. That is exactly what a ctypes CFUNCTYPE
// callback does -- it swaps in a fresh tstate (gilstate_counter == 0, so
// PyGILState_Check() wrongly reports "no GIL") and then acquires the GIL.
// Attaching again there is fatal:
//     Fatal Python error: _PyThreadState_Attach: non-NULL old thread state
// A genuine SDK worker thread has no tstate at all, so it still gets attached.
inline bool attached() {
    return PyThreadState_GetUnchecked() != nullptr;
}

// Call a Python callable, discarding its return value. Returns nullptr and
// leaves the Python error indicator set when the call raised.
// GIL must be held.
//
// PyObject_Vectorcall, NOT PyObject_CallObject: despite the name, the 2nd
// parameter of PyObject_CallObject is a **tuple**
// ("Call a callable object with the argument tuple args"), not an execl-style
// NULL-terminated array. Handing it a raw PyObject*[] makes CPython read
// ob_size out of the first element -- garbage -- and crash with 0xC0000005.
// Vectorcall takes the array plus an explicit count, which is exactly what we
// already have, so the stack/vector juggling is not needed either.
inline PyObject *call_python(nb::object fn, nb::object *args, std::size_t n) {
    return PyObject_Vectorcall(fn.ptr(),
                               reinterpret_cast<PyObject *const *>(args),
                               n, nullptr);
}

// Fetch + report + clear a pending Python exception. Must hold the GIL.
inline void fetch_and_report(const char *name) {
    PyObject *type = nullptr, *value = nullptr, *tb = nullptr;
    PyErr_Fetch(&type, &value, &tb);
    PyErr_NormalizeException(&type, &value, &tb);

    // The UTF-8 buffer returned by PyUnicode_AsUTF8AndSize is owned by the str
    // object, so it must be copied out before that object is released --
    // otherwise msg would dangle by the time snprintf reads it.
    char mbuf[256];
    const char *msg = "unknown error";
    if (value) {
        PyObject *s = PyObject_Str(value);
        if (s) {
            Py_ssize_t n = 0;
            const char *c = PyUnicode_AsUTF8AndSize(s, &n);
            if (c && n > 0) {
                Py_ssize_t copy = n < (Py_ssize_t)sizeof(mbuf) - 1
                                      ? n
                                      : (Py_ssize_t)sizeof(mbuf) - 1;
                std::memcpy(mbuf, c, static_cast<std::size_t>(copy));
                mbuf[copy] = '\0';
                msg = mbuf;
            }
            Py_DECREF(s);
        }
    }
    char buf[512];
    std::snprintf(buf, sizeof(buf),
                  "unify_dh_gen: callback '%s' raised: %s", name, msg);
    nb::print(buf);

    PyErr_Clear();
    Py_XDECREF(type);
    Py_XDECREF(value);
    Py_XDECREF(tb);
}

// set_fXxx(cb): subscribe only.
//
// Unsubscribing is a separate unbind_fXxx() rather than set_fXxx(None): neither
// nb::object nor nb::handle accepts None as a parameter (their caster requires
// isinstance<T>, which is false for None since neither has a handle_type), and
// a zero-arg unbind is both type-safe and clearer at the call site.
inline nb::object setter(const char *name) {
    return nb::cpp_function(
        [name](nb::object cb) { set(name, std::move(cb)); },
        nb::name(name));
}

// unbind_fXxx(): drop the subscription. Safe to call when not subscribed.
inline nb::object unbinder(const char *name) {
    return nb::cpp_function(
        [name]() { clear(name); },
        nb::name(name));
}

// bind_fXxx(cb): subscribe AND return the C function pointer address in one
// call, ready to hand to CLIENT_xxx.
//
// Why not two steps (set_ then fetch pointer): there is a race -- the callback
// can fire before the pointer reaches the SDK -- and the user has to remember
// to call set_ *before* passing the pointer. With one call the correct usage
// falls out naturally:
//     ptr = unify_dh_gen.bind_fRealDataCallBack(on_data)
//     unify_dh_gen.CLIENT_SetRealDataCallBack(login, 0, ptr, 0)
//
// Returns std::uintptr_t rather than a capsule: the existing function bindings
// already expose SDK callback parameters as std::uintptr_t (see
// parse.classify_param -> 'funcptr'), so the two sides line up exactly.
// The wrapper itself is returned as nb::object (type-erased); calling it from
// Python yields the address as an int.
inline nb::object binder(const char *name, void *fn) {
    return nb::cpp_function(
        [name, fn](nb::object cb) -> std::uintptr_t {
            set(name, std::move(cb));
            return reinterpret_cast<std::uintptr_t>(fn);
        },
        nb::name(name));
}

// Struct array argument -> Python list of **borrowed views** (no copy, no
// ownership). The SDK owns the buffer and invalidates it once the callback
// returns, so the views are only valid for the duration of the call; copy the
// fields you need to keep.
template <typename T>
inline nb::list as_list(T *ptr, long long n) {
    nb::list lst;
    if (!ptr || n <= 0)
        return lst;
    for (long long i = 0; i < n; ++i)
        lst.append(nb::cast(ptr + i));
    return lst;
}

// Single struct pointer argument -> borrowed view. NULL becomes None, never
// dereferenced.
template <typename T>
inline nb::object view(T *ptr) {
    if (!ptr)
        return nb::object();
    return nb::cast(ptr);
}

}  // namespace dhcb

// void-returning callback: fetch slot -> call -> discard result -> report &
// swallow any exception. The body is factored into a lambda so both GIL
// branches share it (the nb::object args array is fine inside a lambda body;
// at macro scope a zero-argument call would need a size-0 array guard).
#define DH_CB_VOID(NAME, ...)                                                  \
    do {                                                                       \
        auto _dh_body = [&]() {                                                \
            nb::object _dh_cb = dhcb::get(NAME);                              \
            if (_dh_cb.is_valid()) {                                           \
                nb::object _dh_args[] = { __VA_ARGS__ };                       \
                PyObject *_dh_r = dhcb::call_python(                          \
                    _dh_cb, _dh_args,                                          \
                    sizeof(_dh_args) / sizeof(_dh_args[0]));                  \
                if (_dh_r)                                                     \
                    Py_DECREF(_dh_r);                                          \
                else                                                           \
                    dhcb::fetch_and_report(NAME);                              \
            }                                                                  \
        };                                                                     \
        if (dhcb::attached())                                                  \
            _dh_body();                                                        \
        else {                                                                 \
            nb::gil_scoped_acquire _dh_gil;                                    \
            _dh_body();                                                        \
        }                                                                      \
    } while (0)

// Zero-argument variant: a zero-length array is not valid C++, so callbacks
// that take no parameters get their own macro.
#define DH_CB_VOID0(NAME)                                                      \
    do {                                                                       \
        auto _dh_body = [&]() {                                                \
            nb::object _dh_cb = dhcb::get(NAME);                              \
            if (_dh_cb.is_valid()) {                                           \
                PyObject *_dh_r = dhcb::call_python(_dh_cb, nullptr, 0);      \
                if (_dh_r)                                                     \
                    Py_DECREF(_dh_r);                                          \
                else                                                           \
                    dhcb::fetch_and_report(NAME);                              \
            }                                                                  \
        };                                                                     \
        if (dhcb::attached())                                                  \
            _dh_body();                                                        \
        else {                                                                 \
            nb::gil_scoped_acquire _dh_gil;                                    \
            _dh_body();                                                        \
        }                                                                      \
    } while (0)

// Value-returning callback (usually an int status code): return DEF when
// unsubscribed, on exception, or when the callback returns a non-integer.
#define DH_CB_RET(NAME, DEF, ...)                                              \
    ([&]() -> int {                                                            \
        auto _dh_body = [&]() -> int {                                         \
            nb::object _dh_cb = dhcb::get(NAME);                              \
            if (!_dh_cb.is_valid())                                            \
                return (DEF);                                                  \
            nb::object _dh_args[] = { __VA_ARGS__ };                           \
            PyObject *_dh_r = dhcb::call_python(                              \
                _dh_cb, _dh_args,                                              \
                sizeof(_dh_args) / sizeof(_dh_args[0]));                      \
            if (!_dh_r) {                                                      \
                dhcb::fetch_and_report(NAME);                                  \
                return (DEF);                                                  \
            }                                                                  \
            int _dh_out = (DEF);                                               \
            if (PyLong_Check(_dh_r))                                           \
                _dh_out = static_cast<int>(PyLong_AsLong(_dh_r));              \
            Py_DECREF(_dh_r);                                                  \
            return _dh_out;                                                    \
        };                                                                     \
        if (dhcb::attached())                                                  \
            return _dh_body();                                                 \
        nb::gil_scoped_acquire _dh_gil;                                        \
        return _dh_body();                                                     \
    }())
'''
